# Generated by Django 6.0.1 on 2026-02-17 04:49

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('icon', models.CharField(help_text='Font Awesome icon class', max_length=50)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Facilities',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('established_year', models.IntegerField(validators=[django.core.validators.MinValueValidator(1800)])),
                ('college_type', models.CharField(choices=[('government', 'Government'), ('private', 'Private'), ('deemed', 'Deemed University')], max_length=20)),
                ('city', models.CharField(choices=[('mysore', 'Mysore'), ('bangalore', 'Bangalore')], max_length=50)),
                ('address', models.TextField()),
                ('pincode', models.CharField(max_length=10)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('website', models.URLField()),
                ('affiliated_to', models.CharField(max_length=255)),
                ('approved_by', models.CharField(max_length=255)),
                ('accreditation', models.CharField(blank=True, choices=[('A++', 'A++'), ('A+', 'A+'), ('A', 'A'), ('B++', 'B++'), ('B+', 'B+'), ('B', 'B')], max_length=10, null=True)),
                ('naac_grade', models.CharField(blank=True, max_length=10)),
                ('nirf_rank', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('campus_area', models.DecimalField(decimal_places=2, help_text='in acres', max_digits=10)),
                ('total_students', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('faculty_count', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('facilities', models.JSONField(default=list, help_text='List of available facilities')),
                ('placement_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('average_package', models.DecimalField(blank=True, decimal_places=2, help_text='in LPA', max_digits=10, null=True)),
                ('highest_package', models.DecimalField(blank=True, decimal_places=2, help_text='in LPA', max_digits=10, null=True)),
                ('top_recruiters', models.JSONField(blank=True, default=list)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='colleges/logos/')),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to='colleges/banners/')),
                ('gallery_images', models.JSONField(blank=True, default=list)),
                ('description', models.TextField()),
                ('short_description', models.CharField(max_length=500)),
                ('meta_description', models.CharField(blank=True, max_length=160)),
                ('meta_keywords', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('overall_rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('total_reviews', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-is_featured', '-overall_rating', 'name'],
                'indexes': [models.Index(fields=['city', 'is_active'], name='colleges_co_city_f34773_idx'), models.Index(fields=['college_type'], name='colleges_co_college_b33b1d_idx'), models.Index(fields=['-overall_rating'], name='colleges_co_overall_fa92bf_idx')],
            },
        ),
        migrations.CreateModel(
            name='CollegeReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewer_name', models.CharField(max_length=100)),
                ('reviewer_email', models.EmailField(max_length=254)),
                ('course_studied', models.CharField(max_length=100)),
                ('batch_year', models.IntegerField()),
                ('academics_rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('infrastructure_rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('placements_rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('faculty_rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('title', models.CharField(max_length=200)),
                ('review_text', models.TextField()),
                ('is_verified', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='colleges.college')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('level', models.CharField(choices=[('ug', 'Undergraduate'), ('pg', 'Postgraduate'), ('diploma', 'Diploma'), ('certificate', 'Certificate')], max_length=20)),
                ('stream', models.CharField(choices=[('engineering', 'Engineering'), ('medicine', 'Medicine'), ('commerce', 'Commerce'), ('science', 'Science'), ('arts', 'Arts'), ('management', 'Management'), ('law', 'Law'), ('pharmacy', 'Pharmacy')], max_length=50)),
                ('duration_years', models.DecimalField(decimal_places=1, max_digits=3)),
                ('total_fees', models.DecimalField(decimal_places=2, max_digits=10)),
                ('per_year_fees', models.DecimalField(decimal_places=2, max_digits=10)),
                ('seats_available', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('eligibility', models.TextField()),
                ('entrance_exams', models.JSONField(default=list)),
                ('description', models.TextField()),
                ('syllabus', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='colleges.college')),
            ],
            options={
                'ordering': ['college', 'level', 'name'],
                'unique_together': {('college', 'name', 'level')},
            },
        ),
    ]
